//! Port of src/common/map/MapReaderConstants.h

pub const g_szBackgroundConversion: [&str; 26] = [
    "Land_Classic.png",
    "Castle_Dungeon.png",
    "Desert_Pyramids.png",
    "Ghost_GhostHouse.png",
    "Underground_Cave.png",
    "Clouds_AboveTheClouds.png",
    "Castle_GoombaHall.png",
    "Platforms_GreenSpottedHills.png",
    "Snow_SnowTrees.png",
    "Desert_Desert.png",
    "Underground_BrownRockWall.png",
    "Land_CastleWall.png",
    "Clouds_Clouds.png",
    "Land_GreenMountains.png",
    "Land_InTheTrees.png",
    "Battle_Manor.png",
    "Platforms_JaggedGreenStones.png",
    "Underground_RockWallAndPlants.png",
    "Underground_DarkPipes.png",
    "Bonus_StarryNight.png",
    "Platforms_CloudsAndWaterfalls.png",
    "Battle_GoombaPillars.png",
    "Bonus_HillsAtNight.png",
    "Castle_CastlePillars.png",
    "Land_GreenHillsAndClouds.png",
    "Platforms_BlueSpottedHills.png",
];
