//! Not in upstream: the length SDL2_mixer gives every sound and track in data/, which the virtual mixer
//! (sfx.rs) turns into channel and music end times. The table is the input for making the virtual mixer
//! independent of the backend's decoder (docs/ARCHITECTURE_V2.md, Audio).
//!
//! Regenerate with `cargo run --example sfx_durations > crates/smw-core/src/common/sfx_durations.txt`.

use sdl2::sys::mixer::{Mix_CloseAudio, Mix_FreeChunk, Mix_FreeMusic, Mix_LoadMUS, Mix_LoadWAV_RW, Mix_Music, Mix_OpenAudio, Mix_QuerySpec};
use sdl2::sys::{SDL_InitSubSystem, SDL_QuitSubSystem, SDL_RWFromFile, SDL_INIT_AUDIO, AUDIO_S16};
use std::collections::HashMap;
use std::ffi::CString;
use std::fmt::Write;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

pub const TABLE: &str = include_str!("sfx_durations.txt");

struct Table {
    sounds: HashMap<&'static str, u32>,
    tracks: HashMap<&'static str, f64>,
}

fn table() -> &'static Table {
    static TABLE_PARSED: OnceLock<Table> = OnceLock::new();
    TABLE_PARSED.get_or_init(|| {
        let mut t = Table { sounds: HashMap::new(), tracks: HashMap::new() };
        for line in TABLE.lines().filter(|l| !l.starts_with('#')) {
            let f: Vec<&str> = line.split(' ').collect();
            match f[0] {
                "chunk" => {
                    t.sounds.insert(f[1], f[3].parse().unwrap());
                }
                "music" => {
                    t.tracks.insert(f[1], f[2].parse().unwrap());
                }
                _ => panic!("sfx_durations.txt: {}", line),
            }
        }
        t
    })
}

/// A sound's length in milliseconds at 44100 Hz, S16, stereo, by its data-relative path.
pub fn sound_ms(name: &str) -> Option<u32> {
    table().sounds.get(name).copied()
}

/// A track's `Mix_MusicDuration` in seconds, by its data-relative path.
pub fn track_seconds(name: &str) -> Option<f64> {
    table().tracks.get(name).copied()
}

extern "C" {
    // SDL_mixer 2.6+, missing from sdl2-sys.
    fn Mix_MusicDuration(music: *mut Mix_Music) -> f64;
}

fn files(dir: &Path, ext: &str, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            files(&path, ext, out);
        } else if path.extension().is_some_and(|e| e.eq_ignore_ascii_case(ext)) {
            out.push(path);
        }
    }
}

/// Opens SDL_mixer as `sfx_init` does on the dummy audio driver (44100 Hz, S16, stereo) and measures every
/// `.wav` under `data_dir` as a chunk (`Mix_Chunk::alen`, and the milliseconds `chunk_duration_ms` makes of it)
/// and every `.ogg` as music (`Mix_MusicDuration`). Returns the table's text.
pub fn measure(data_dir: &Path) -> String {
    let mut out = String::from(
        "# Generated by `cargo run --example sfx_durations`: SDL2_mixer on the dummy audio driver.\n\
         # chunk <path> <Mix_Chunk::alen> <ms>, music <path> <Mix_MusicDuration>; paths relative to data/.\n",
    );
    unsafe {
        std::env::set_var("SDL_AUDIODRIVER", "dummy");
        SDL_InitSubSystem(SDL_INIT_AUDIO);
        assert_eq!(Mix_OpenAudio(44100, AUDIO_S16 as u16, 2, 2048), 0, "Mix_OpenAudio failed");
        let (mut frequency, mut format, mut channels) = (0, 0u16, 0);
        Mix_QuerySpec(&mut frequency, &mut format, &mut channels);
        let _ = writeln!(out, "# spec {} Hz, format {:#06x}, {} channels", frequency, format, channels);
        let bytes_per_second = frequency as u64 * channels as u64 * ((format & 0xFF) as u64 / 8);

        let rel = |p: &Path| p.strip_prefix(data_dir).unwrap().to_string_lossy().replace('\\', "/");
        let mut sounds = Vec::new();
        files(data_dir, "wav", &mut sounds);
        sounds.sort_by_key(|p| rel(p));
        for path in &sounds {
            let cpath = CString::new(path.to_string_lossy().as_bytes()).unwrap();
            let chunk = Mix_LoadWAV_RW(SDL_RWFromFile(cpath.as_ptr(), b"rb\0".as_ptr() as *const _), 1);
            assert!(!chunk.is_null(), "Mix_LoadWAV_RW failed for {}", path.display());
            let alen = (*chunk).alen;
            let _ = writeln!(out, "chunk {} {} {}", rel(path), alen, alen as u64 * 1000 / bytes_per_second);
            Mix_FreeChunk(chunk);
        }

        let mut tracks = Vec::new();
        files(data_dir, "ogg", &mut tracks);
        tracks.sort_by_key(|p| rel(p));
        for path in &tracks {
            let cpath = CString::new(path.to_string_lossy().as_bytes()).unwrap();
            let music = Mix_LoadMUS(cpath.as_ptr());
            assert!(!music.is_null(), "Mix_LoadMUS failed for {}", path.display());
            let _ = writeln!(out, "music {} {:?}", rel(path), Mix_MusicDuration(music));
            Mix_FreeMusic(music);
        }

        Mix_CloseAudio();
        SDL_QuitSubSystem(SDL_INIT_AUDIO);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_matches_sdl_mixer() {
        let measured = measure(Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../../data")));
        for (n, (want, got)) in TABLE.lines().zip(measured.lines()).enumerate() {
            assert_eq!(want, got, "line {} of sfx_durations.txt", n + 1);
        }
        assert_eq!(TABLE.lines().count(), measured.lines().count());
    }
}
