name: Relay

on:
  push:
    branches: [main]
    paths:
      - relay/**
      - Cargo.toml
      - Cargo.lock
      - src/common/file_io.rs
      - src/common_netplay/**
      - src/globals/**
      - src/server/**
      - tools/ref/unordered_map_order.txt
      - Dockerfile
      - .dockerignore
      - .github/workflows/relay.yml
      - .github/workflows/build_relay.yml
  pull_request:
    paths:
      - relay/**
      - Cargo.toml
      - Cargo.lock
      - src/common/file_io.rs
      - src/common_netplay/**
      - src/globals/**
      - src/server/**
      - tools/ref/unordered_map_order.txt
      - Dockerfile
      - .dockerignore
      - .github/workflows/relay.yml
      - .github/workflows/build_relay.yml
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  relay:
    uses: ./.github/workflows/build_relay.yml
    with:
      push: ${{ github.event_name != 'pull_request' }}
